from enum import Enum


class ErrorCode(Enum):
    '''
        THIS PART CONTAINS GENERAL ERROR CODES
    '''
    OBJECT_NOT_FOUND = 10001
    NOT_UPDATED = 10002
    NOT_INSERTED = 10009
    NOT_DELETED = 10003
    UNEXPECTED_DATA = 10009
    '''
        THIS PART CONTAINS ERROR CODE FOR AUTH SERVICE
    '''
    INCORRECT_USERNAME_OR_PASSWORD = 10004
    USER_NOT_FOUND = 10005
    '''
        THIS PART CONTAINS ERROR CODE FOR CONTENT ADDITION
    '''
    CONTENT_ID_IS_ALREADY_EXISTS = 10013
    INVALID_OTP_OR_EXPIRED = 10014
    RESET_REQUEST_NOT_FOUND = 10015